### Write a python code for decoding (7, 4) Block code

In [1]:
import numpy as np

# Define the generator matrix
G = np.array([[1,0,0,0,1,1,1],
              [0,1,0,0,1,0,1],
              [0,0,1,0,1,1,0],
              [0,0,0,1,0,1,1]])

# Define the parity-check matrix
H = np.array([[1,1,1,0,1,0,0],
              [1,0,1,1,0,1,0],
              [1,1,0,1,0,0,1]])

# Define the received codeword
r = np.array([1,0,0,1,1,0,1])

# Calculate the syndrome
s = np.dot(r, H.T) % 2

print(s)
print(r)

for i in range(len(H.T)):
    a = (s == H.T[i,:])
    if a[0] == 1 & a[1] == 1 & a[2] == 1:
        print("error_pos = ",i)
        break
    else : 
        print('no error')
        
e = np.array([0,0,0,0,0,0,0])
e[i] = e[i] + 1
c = (r + e)%2
print(c)

m = np.dot(c[:4], np.identity(4)) % 2

print("Received sequence:", r)
print("Original message:", m)
print("Corrected codeword:", c)

[0 0 1]
[1 0 0 1 1 0 1]
no error
no error
no error
no error
no error
no error
error_pos =  6
[1 0 0 1 1 0 0]
Received sequence: [1 0 0 1 1 0 1]
Original message: [1. 0. 0. 1.]
Corrected codeword: [1 0 0 1 1 0 0]
