In [1]:
import numpy as np

u = np.random.randint(2,size=(1,100)).flatten() # 100 bits 생성
u2 = u.reshape(10,10) # block interleaver를 하기 위해서 10X10 행렬로 변환
u3 = []
u4 = [np.array([])]
for i in range(10):
    for j in range(10):
        u3.append(u2[j][i]) # block interleaver를 적용한 bits
        
matrix = [[-1] * 10 for _ in range(20)]
for i in range(9,-1,-1):
    for j in range(0,10):
        matrix[j+(9-i)][i] = u2[j][i] #helical interleaver를 적용한 bits
        

print(u)
print(u2)
print(u3)
print(matrix)
# matrix = np.array(matrix)
for row in matrix:
    u4.extend(value for value in row if value != -1)
print(u4)


[0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0
 1 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1
 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0]
[[0 0 1 1 0 1 1 1 0 1]
 [1 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 1 0 1 0 1 1 1]
 [0 0 1 1 1 1 0 1 0 1]
 [1 0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 0 1 1 0 1 1]
 [0 1 1 0 0 1 0 1 1 0]]
[0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0]
[[-1, -1, -1, -1, -1, -1, -1, -1, -1, 1], [-1, -1, -1, -1, -1, -1, -1, -1, 0, 1], [-1, -1, -1, -1, -1, -1, -1, 1, 1, 1], [-1, -1, -1, -1, -1, -1, 1, 1, 1, 1], [-1, -1, -1, -1, -1, 1, 1, 0, 1, 1], [-1, -1, -1, -1, 0, 1, 0, 1, 0, 1], [-1, -1, -1, 1, 0, 0, 0, 1, 1, 0

In [2]:
def turbo_enc(u,u3):
    state1 = [0, 0]
    state2 = [0, 0]
    encoded_data = []
    encoded_data1 = []

    for bit in u:
        # Calculate the encoded bits
        encoded_bits = [(bit),((bit + state1[0] + state1[1] + state1[1]) % 2)]
        # Shift the state
        state1.insert(0, (bit + state1[0] + state1[1]) % 2)
        state1.pop()
        # Append the encoded bits to the output
        encoded_data.extend(encoded_bits)

    indices = list(range(2, 301, 3)) # 삽입해야하는 index 번호
    
    for bit in u3:
        # Calculate the encoded bits
        encoded_bits1 = [((bit + state2[0] + state2[1] + state2[1]) % 2)]
        # Shift the state
        state2.insert(0, (bit + state2[0] + state2[1]) % 2)
        state2.pop()
        # Append the encoded bits to the output
        encoded_data1.extend(encoded_bits1)
        
    for index, value in zip(indices, encoded_data1):
        encoded_data.insert(index, value)
        
    return encoded_data

In [6]:
enc = turbo_enc(u,u3)
print(enc,np.size(enc))

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1] 300
